[build]
rustflags = ["-Dwarnings"]

[target.'cfg(all())']
rustflags = ["-Dclippy::all"]

[alias]
lint = "clippy --all-targets --all-features -- -D warnings"
check-all = "check --all-targets --all-features"
format = "fmt --all"
format-check = "fmt --all -- --check"
